[build]
target = "frontend/index.html"
dist = "target/dist"
release = false

# TODO fix: not working
# [[hooks]]
# stage = "build"
# command = "bash"
# command_arguments = [
#     "-c",
#     "npx tailwindcss -i frontend/src/tailwind.css -o $TRUNK_STAGING_DIR/tailwind.css -m -c frontend/tailwind.config.js",
# ]
# * npx tailwindcss -i frontend/src/tailwind.css -o frontend/tailwind.css -m -c frontend/tailwind.config.js

