[build]
target = "frontend/index.html"
dist = "target/dist"
release = true


[[hooks]]
stage = "build"
command = "C:\\Program Files\\Git\\bin\\sh.exe" # `sh` is in the git installation folder
command_arguments = [
    "-c",
    "npx tailwindcss -i frontend/src/tailwind.css -o target/dist/.stage/tailwind.css -m -c frontend/tailwind.config.js",
]